"""Utility to maintain the 5-letter dictionary used in CodeQuest."""

WORDS = []
WORDS.extend("about actor acute adept admit adobe adopt adore adult after again agent agile agony agree ahead aisle alarm album alert alike alive allow alpha alter amber amuse angel anger angle angry ankle apple apply apron argue arise armed arrow aside asset audio audit aural avail awake award aware awful badge baker basil basic batch beach beard beast begin being belly below bench berry birth black blade blame blank blaze bleed bless blind block blood bloom board boast bonus booth boost bound brain brand brass brave bread break brick bride brief bring brisk broad brood brown brush build bunch burst".split())
WORDS.extend("cabin cable cache cadet camel cameo canal candy canoe canon cargo carve catch cause cedar chain chair chalk charm chart chase cheat check cheer chess chest chief child chili china choir chord chore chuck cider civic claim class clean clear clerk click cliff climb clock close cloud coach coast coral corgi could count court craft crane crash crazy cream creek crest crisp cross crowd crown crush crypt curry curve cycle daily dairy dance datum dealt debut decay decor delay delta demon dense diary digit diner dingo dirty dodge donut doubt dozen draft drain drake drama drawn dream dress drift drink drive droid drown druid eager eagle early earth ebony edict eight elbow elder elect elite elope ember emote empty enact endow enjoy ensue enter envoy equal equip erase ether ethic evade event every exact exalt excel exile exist expel extra".split())
WORDS.extend("fable facet fairy faith false fancy farce fatal favor feast fence ferry fever fiber field fiery fifth fifty fight final finch flair flame flask fleet flesh flick fling float flood floor flour flute focus folly force forge forum found frame fresh fried frost fruit gauge gavel gazer gears geeky genie genre ghost giant giddy gifts glade gland glare glass glide gloom glory glove gnome grace grade grain grand grant grape graph grasp grass grave great greed green greet grill grind groan groom group grove guard guess guide guild guilt habit haiku hairy hands happy hardy hasty hatch haunt haven hazel heart heath heavy hedge heist hello hence heron hilly hinge hobby honor honey horse hotel house hover human humid humor hurry hutch hydra ideal idiom idler image imply index inept infer ingot inner input irony issue ivory".split())
WORDS.extend("jelly jewel jolly judge juice jumbo jumpy junta karma kayak kebab khaki kiosk kitty knack kneel knife knock known koala label labor laces lance lanky laser later laugh layer leafy learn leash leave legal lemon level lever light lilac limit linen lithe liver livid lobby local logic loner loose loved lover lower loyal lucky lumen lunar lunch lyric magic maize major maker mango manor maple march marsh mason match medal media merit metal meter micro might miner minor minty mirth model modem moist money month moral motel motor mount mouse mover movie music musty nacho nadir nanny nasal nasty naval noble noise north novel nudge nurse".split())
WORDS.extend("oasis ocean octet odium offer often olden olive omega onion opera orbit order organ otter ounce outer overt owner oxide ozone paddy pagan paint panda panel panic paper pasta patch patio pause peach pearl pecan pedal peony perch phase phone photo piano picky piece piety pilot pinch piney pinky pique pitch pixel pizza place plaid plain plait plane plant plaza plead plush poems point poise polar polka pound power press price pride prime print prism privy prize probe prone proof proud prove proxy psalm punch pupil puppy purse queen query quest quick quiet quill quilt quirk quota quote radar radio rainy raise rally ranch range rapid ratio reach ready realm rebel refer relax renew reply retro rhyme rider ridge rifle right rigid rival river roast robin robot rocky rogue roomy rough round route rover royal rugby rumor rural rusty".split())
WORDS.extend("sable salsa salty sandy sassy satin sauce scale scarf scare scent scoop scope score scout scrap screw seize sense serum serve seven sewer shack shade shaft shake shall shame shape share shark sharp sheep sheer sheet shelf shell shift shine shiny shock shook shoot shore short shout shove shown shrub shrug sight sigma silky silly since siren skate skill skirt skull slack slate slave sleek sleep slice slide slope smack small smart smile smoke snack snake sneak snoop sober solar solid solve sonic sound south space spade spare spark speak spear speck speed spell spice spicy spike spill spine spiny spire spite split spoil spoke spoon sport spout spray spree sprig spunk squad squid stack stage stain stair stake stale stalk stamp stand stare start state steam steel steep steer stern stick stiff still sting stink stock stomp stone stool store storm story stout stove strap straw strip stuck study stuff style sugar suite sunny super surge sushi swamp swear sweat sweep sweet swell swept swift swing sword".split())
WORDS.extend("table taffy taken tango taper taste teach tease tempo tenth thank theft their theme there thick thief thing think third thorn those three throb throw thumb tiara tiger tight timer tired toast today token tonal tonic tooth topic torch total toxic trace track trade trail train tramp trash treat trend triad trial tribe trick tried tripe trite troll troop trout truce truck truly trunk trust truth tulip tumor tuned tunic turbo twice twine twirl twist uncle under unite unity until upper urban usage usher vague valet valid valor value valve vapor vault vegan venom venue verse vivid vocal vodka voice voids vogue voter vouch vowel wacky wafer wager wagon waist waltz watch water weary weave wedge weigh whale wheat wheel where which whine whirl white whole whoop whose widow width wield wilds wince winch windy wiser witch witty woken woman wonky world worry wound woven wraps wreck wrist write wrong yacht yearn yeast yield young youth zebra zesty zonal".split())
WORDS = [w for w in WORDS if len(w) == 5 and w.isalpha()]

if __name__ == "__main__":
    print(len(WORDS))
